pre-release-commit-message = "release {{crate_name}} {{version}}"
disable-tag = true
disable-push = true
disable-publish = true
no-dev-version = true
enable-all-features = true
consolidate-commits = false
pre-release-replacements = [
  {file="CHANGELOG.md", search="Unreleased", replace="v{{version}}", prerelease=false},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}", prerelease=false},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n\n## [Unreleased] - ReleaseDate\n\n[Commits](https://github.com/twitch-rs/twitch_types/compare/v{{version}}...Unreleased)", prerelease=false},
  {file="README.md", search="twitch_types/[a-z0-9\\.-]+/twitch_types", replace="{{crate_name}}/{{version}}/{{crate_name}}", prerelease=true},
]